# Generated by Django 4.2.4 on 2023-09-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productalbum',
            name='image_description',
        ),
        migrations.AddField(
            model_name='productalbum',
            name='image_view',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productalbum',
            name='image_url',
            field=models.ImageField(upload_to='album'),
        ),
    ]
