# Generated by Django 4.2.4 on 2023-10-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_productalbum_image_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fuel_consumption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='maintance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
